resolver: lts-9.2
packages: [.]

nix:
    packages: [openssh,git]

extra-deps:
- aeson-extra-0.4.0.0
- containers-0.5.10.2
- fmt-0.5.0.0
- log-warper-1.7.1
- time-units-1.0.0
- recursion-schemes-5
- universum-0.8.0

flags: {}
extra-package-dbs: []
