resolver: lts-9.2
packages:
- '.'
- location:
    git: https://github.com/serokell/acid-state.git
    commit: 95fce1dbada62020a0b2d6aa2dd7e88eadd7214b
  extra-dep: true

nix:
    packages: [openssh,git]

extra-deps:
- aeson-extra-0.4.0.0
- time-units-1.0.0
- recursion-schemes-5
- log-warper-1.2.0
- universum-0.6.1

flags: {}
extra-package-dbs: []
