resolver: lts-6.1

# Local packages, usually specified by relative directory name
packages:
- '.'
- location:
    git: https://github.com/serokell/msgpack-haskell.git
    commit: 20691fa4f85ef2a75c5808a5b2e69fd28fdaa159
  extra-dep: true
  subdirs:
    - msgpack

nix:
    enable: false
    packages: [openssh,git]

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps: []

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
