resolver: lts-8.2
packages:
- '.'
nix:
    packages: [openssh,git]

extra-deps:
- aeson-extra-0.4.0.0
- time-units-1.0.0
- recursion-schemes-5
- log-warper-0.2.1
- universum-0.2.1

flags: {}
extra-package-dbs: []
